/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RunpodRouteImport } from './routes/runpod'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as OpenrouterRouteImport } from './routes/openrouter'
import { Route as NowRouteImport } from './routes/now'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PProjectRouteImport } from './routes/p.$project'
import { Route as PProjectIndexRouteImport } from './routes/p.$project.index'
import { Route as PProjectTriggersRouteImport } from './routes/p.$project.triggers'
import { Route as PProjectSettingsRouteImport } from './routes/p.$project.settings'
import { Route as PProjectInboxRouteImport } from './routes/p.$project.inbox'
import { Route as PProjectFilesRouteImport } from './routes/p.$project.files'
import { Route as PProjectBoardRouteImport } from './routes/p.$project.board'
import { Route as PProjectAdrsRouteImport } from './routes/p.$project.adrs'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as PProjectRunsIndexRouteImport } from './routes/p.$project.runs.index'
import { Route as PProjectReviewIndexRouteImport } from './routes/p.$project.review.index'
import { Route as PProjectTasksTaskIdRouteImport } from './routes/p.$project.tasks.$taskId'
import { Route as PProjectRunsRunIdRouteImport } from './routes/p.$project.runs.$runId'
import { Route as PProjectReviewTaskIdRouteImport } from './routes/p.$project.review.$taskId'
import { Route as PProjectBoardTasksTaskIdRouteImport } from './routes/p.$project.board.tasks.$taskId'
import { Route as ApiAttachmentsProjectTaskIdNameRouteImport } from './routes/api/attachments.$project.$taskId.$name'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RunpodRoute = RunpodRouteImport.update({
  id: '/runpod',
  path: '/runpod',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenrouterRoute = OpenrouterRouteImport.update({
  id: '/openrouter',
  path: '/openrouter',
  getParentRoute: () => rootRouteImport,
} as any)
const NowRoute = NowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectRoute = PProjectRouteImport.update({
  id: '/p/$project',
  path: '/p/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIndexRoute = PProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectRoute,
} as any)
const PProjectTriggersRoute = PProjectTriggersRouteImport.update({
  id: '/triggers',
  path: '/triggers',
  getParentRoute: () => PProjectRoute,
} as any)
const PProjectSettingsRoute = PProjectSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PProjectRoute,
} as any)
const PProjectInboxRoute = PProjectInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => PProjectRoute,
} as any)
const PProjectFilesRoute = PProjectFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => PProjectRoute,
} as any)
const PProjectBoardRoute = PProjectBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => PProjectRoute,
} as any)
const PProjectAdrsRoute = PProjectAdrsRouteImport.update({
  id: '/adrs',
  path: '/adrs',
  getParentRoute: () => PProjectRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectRunsIndexRoute = PProjectRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => PProjectRoute,
} as any)
const PProjectReviewIndexRoute = PProjectReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => PProjectRoute,
} as any)
const PProjectTasksTaskIdRoute = PProjectTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => PProjectRoute,
} as any)
const PProjectRunsRunIdRoute = PProjectRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => PProjectRoute,
} as any)
const PProjectReviewTaskIdRoute = PProjectReviewTaskIdRouteImport.update({
  id: '/review/$taskId',
  path: '/review/$taskId',
  getParentRoute: () => PProjectRoute,
} as any)
const PProjectBoardTasksTaskIdRoute =
  PProjectBoardTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => PProjectBoardRoute,
  } as any)
const ApiAttachmentsProjectTaskIdNameRoute =
  ApiAttachmentsProjectTaskIdNameRouteImport.update({
    id: '/api/attachments/$project/$taskId/$name',
    path: '/api/attachments/$project/$taskId/$name',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/inbox': typeof InboxRoute
  '/now': typeof NowRoute
  '/openrouter': typeof OpenrouterRoute
  '/resources': typeof ResourcesRoute
  '/runpod': typeof RunpodRoute
  '/settings': typeof SettingsRoute
  '/p/$project': typeof PProjectRouteWithChildren
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/p/$project/adrs': typeof PProjectAdrsRoute
  '/p/$project/board': typeof PProjectBoardRouteWithChildren
  '/p/$project/files': typeof PProjectFilesRoute
  '/p/$project/inbox': typeof PProjectInboxRoute
  '/p/$project/settings': typeof PProjectSettingsRoute
  '/p/$project/triggers': typeof PProjectTriggersRoute
  '/p/$project/': typeof PProjectIndexRoute
  '/p/$project/review/$taskId': typeof PProjectReviewTaskIdRoute
  '/p/$project/runs/$runId': typeof PProjectRunsRunIdRoute
  '/p/$project/tasks/$taskId': typeof PProjectTasksTaskIdRoute
  '/p/$project/review/': typeof PProjectReviewIndexRoute
  '/p/$project/runs/': typeof PProjectRunsIndexRoute
  '/api/attachments/$project/$taskId/$name': typeof ApiAttachmentsProjectTaskIdNameRoute
  '/p/$project/board/tasks/$taskId': typeof PProjectBoardTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/inbox': typeof InboxRoute
  '/now': typeof NowRoute
  '/openrouter': typeof OpenrouterRoute
  '/resources': typeof ResourcesRoute
  '/runpod': typeof RunpodRoute
  '/settings': typeof SettingsRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/p/$project/adrs': typeof PProjectAdrsRoute
  '/p/$project/board': typeof PProjectBoardRouteWithChildren
  '/p/$project/files': typeof PProjectFilesRoute
  '/p/$project/inbox': typeof PProjectInboxRoute
  '/p/$project/settings': typeof PProjectSettingsRoute
  '/p/$project/triggers': typeof PProjectTriggersRoute
  '/p/$project': typeof PProjectIndexRoute
  '/p/$project/review/$taskId': typeof PProjectReviewTaskIdRoute
  '/p/$project/runs/$runId': typeof PProjectRunsRunIdRoute
  '/p/$project/tasks/$taskId': typeof PProjectTasksTaskIdRoute
  '/p/$project/review': typeof PProjectReviewIndexRoute
  '/p/$project/runs': typeof PProjectRunsIndexRoute
  '/api/attachments/$project/$taskId/$name': typeof ApiAttachmentsProjectTaskIdNameRoute
  '/p/$project/board/tasks/$taskId': typeof PProjectBoardTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/inbox': typeof InboxRoute
  '/now': typeof NowRoute
  '/openrouter': typeof OpenrouterRoute
  '/resources': typeof ResourcesRoute
  '/runpod': typeof RunpodRoute
  '/settings': typeof SettingsRoute
  '/p/$project': typeof PProjectRouteWithChildren
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/p/$project/adrs': typeof PProjectAdrsRoute
  '/p/$project/board': typeof PProjectBoardRouteWithChildren
  '/p/$project/files': typeof PProjectFilesRoute
  '/p/$project/inbox': typeof PProjectInboxRoute
  '/p/$project/settings': typeof PProjectSettingsRoute
  '/p/$project/triggers': typeof PProjectTriggersRoute
  '/p/$project/': typeof PProjectIndexRoute
  '/p/$project/review/$taskId': typeof PProjectReviewTaskIdRoute
  '/p/$project/runs/$runId': typeof PProjectRunsRunIdRoute
  '/p/$project/tasks/$taskId': typeof PProjectTasksTaskIdRoute
  '/p/$project/review/': typeof PProjectReviewIndexRoute
  '/p/$project/runs/': typeof PProjectRunsIndexRoute
  '/api/attachments/$project/$taskId/$name': typeof ApiAttachmentsProjectTaskIdNameRoute
  '/p/$project/board/tasks/$taskId': typeof PProjectBoardTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/inbox'
    | '/now'
    | '/openrouter'
    | '/resources'
    | '/runpod'
    | '/settings'
    | '/p/$project'
    | '/api/trpc/$'
    | '/p/$project/adrs'
    | '/p/$project/board'
    | '/p/$project/files'
    | '/p/$project/inbox'
    | '/p/$project/settings'
    | '/p/$project/triggers'
    | '/p/$project/'
    | '/p/$project/review/$taskId'
    | '/p/$project/runs/$runId'
    | '/p/$project/tasks/$taskId'
    | '/p/$project/review/'
    | '/p/$project/runs/'
    | '/api/attachments/$project/$taskId/$name'
    | '/p/$project/board/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/inbox'
    | '/now'
    | '/openrouter'
    | '/resources'
    | '/runpod'
    | '/settings'
    | '/api/trpc/$'
    | '/p/$project/adrs'
    | '/p/$project/board'
    | '/p/$project/files'
    | '/p/$project/inbox'
    | '/p/$project/settings'
    | '/p/$project/triggers'
    | '/p/$project'
    | '/p/$project/review/$taskId'
    | '/p/$project/runs/$runId'
    | '/p/$project/tasks/$taskId'
    | '/p/$project/review'
    | '/p/$project/runs'
    | '/api/attachments/$project/$taskId/$name'
    | '/p/$project/board/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/inbox'
    | '/now'
    | '/openrouter'
    | '/resources'
    | '/runpod'
    | '/settings'
    | '/p/$project'
    | '/api/trpc/$'
    | '/p/$project/adrs'
    | '/p/$project/board'
    | '/p/$project/files'
    | '/p/$project/inbox'
    | '/p/$project/settings'
    | '/p/$project/triggers'
    | '/p/$project/'
    | '/p/$project/review/$taskId'
    | '/p/$project/runs/$runId'
    | '/p/$project/tasks/$taskId'
    | '/p/$project/review/'
    | '/p/$project/runs/'
    | '/api/attachments/$project/$taskId/$name'
    | '/p/$project/board/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  InboxRoute: typeof InboxRoute
  NowRoute: typeof NowRoute
  OpenrouterRoute: typeof OpenrouterRoute
  ResourcesRoute: typeof ResourcesRoute
  RunpodRoute: typeof RunpodRoute
  SettingsRoute: typeof SettingsRoute
  PProjectRoute: typeof PProjectRouteWithChildren
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiAttachmentsProjectTaskIdNameRoute: typeof ApiAttachmentsProjectTaskIdNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runpod': {
      id: '/runpod'
      path: '/runpod'
      fullPath: '/runpod'
      preLoaderRoute: typeof RunpodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openrouter': {
      id: '/openrouter'
      path: '/openrouter'
      fullPath: '/openrouter'
      preLoaderRoute: typeof OpenrouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now': {
      id: '/now'
      path: '/now'
      fullPath: '/now'
      preLoaderRoute: typeof NowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$project': {
      id: '/p/$project'
      path: '/p/$project'
      fullPath: '/p/$project'
      preLoaderRoute: typeof PProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$project/': {
      id: '/p/$project/'
      path: '/'
      fullPath: '/p/$project/'
      preLoaderRoute: typeof PProjectIndexRouteImport
      parentRoute: typeof PProjectRoute
    }
    '/p/$project/triggers': {
      id: '/p/$project/triggers'
      path: '/triggers'
      fullPath: '/p/$project/triggers'
      preLoaderRoute: typeof PProjectTriggersRouteImport
      parentRoute: typeof PProjectRoute
    }
    '/p/$project/settings': {
      id: '/p/$project/settings'
      path: '/settings'
      fullPath: '/p/$project/settings'
      preLoaderRoute: typeof PProjectSettingsRouteImport
      parentRoute: typeof PProjectRoute
    }
    '/p/$project/inbox': {
      id: '/p/$project/inbox'
      path: '/inbox'
      fullPath: '/p/$project/inbox'
      preLoaderRoute: typeof PProjectInboxRouteImport
      parentRoute: typeof PProjectRoute
    }
    '/p/$project/files': {
      id: '/p/$project/files'
      path: '/files'
      fullPath: '/p/$project/files'
      preLoaderRoute: typeof PProjectFilesRouteImport
      parentRoute: typeof PProjectRoute
    }
    '/p/$project/board': {
      id: '/p/$project/board'
      path: '/board'
      fullPath: '/p/$project/board'
      preLoaderRoute: typeof PProjectBoardRouteImport
      parentRoute: typeof PProjectRoute
    }
    '/p/$project/adrs': {
      id: '/p/$project/adrs'
      path: '/adrs'
      fullPath: '/p/$project/adrs'
      preLoaderRoute: typeof PProjectAdrsRouteImport
      parentRoute: typeof PProjectRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$project/runs/': {
      id: '/p/$project/runs/'
      path: '/runs'
      fullPath: '/p/$project/runs/'
      preLoaderRoute: typeof PProjectRunsIndexRouteImport
      parentRoute: typeof PProjectRoute
    }
    '/p/$project/review/': {
      id: '/p/$project/review/'
      path: '/review'
      fullPath: '/p/$project/review/'
      preLoaderRoute: typeof PProjectReviewIndexRouteImport
      parentRoute: typeof PProjectRoute
    }
    '/p/$project/tasks/$taskId': {
      id: '/p/$project/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/p/$project/tasks/$taskId'
      preLoaderRoute: typeof PProjectTasksTaskIdRouteImport
      parentRoute: typeof PProjectRoute
    }
    '/p/$project/runs/$runId': {
      id: '/p/$project/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/p/$project/runs/$runId'
      preLoaderRoute: typeof PProjectRunsRunIdRouteImport
      parentRoute: typeof PProjectRoute
    }
    '/p/$project/review/$taskId': {
      id: '/p/$project/review/$taskId'
      path: '/review/$taskId'
      fullPath: '/p/$project/review/$taskId'
      preLoaderRoute: typeof PProjectReviewTaskIdRouteImport
      parentRoute: typeof PProjectRoute
    }
    '/p/$project/board/tasks/$taskId': {
      id: '/p/$project/board/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/p/$project/board/tasks/$taskId'
      preLoaderRoute: typeof PProjectBoardTasksTaskIdRouteImport
      parentRoute: typeof PProjectBoardRoute
    }
    '/api/attachments/$project/$taskId/$name': {
      id: '/api/attachments/$project/$taskId/$name'
      path: '/api/attachments/$project/$taskId/$name'
      fullPath: '/api/attachments/$project/$taskId/$name'
      preLoaderRoute: typeof ApiAttachmentsProjectTaskIdNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PProjectBoardRouteChildren {
  PProjectBoardTasksTaskIdRoute: typeof PProjectBoardTasksTaskIdRoute
}

const PProjectBoardRouteChildren: PProjectBoardRouteChildren = {
  PProjectBoardTasksTaskIdRoute: PProjectBoardTasksTaskIdRoute,
}

const PProjectBoardRouteWithChildren = PProjectBoardRoute._addFileChildren(
  PProjectBoardRouteChildren,
)

interface PProjectRouteChildren {
  PProjectAdrsRoute: typeof PProjectAdrsRoute
  PProjectBoardRoute: typeof PProjectBoardRouteWithChildren
  PProjectFilesRoute: typeof PProjectFilesRoute
  PProjectInboxRoute: typeof PProjectInboxRoute
  PProjectSettingsRoute: typeof PProjectSettingsRoute
  PProjectTriggersRoute: typeof PProjectTriggersRoute
  PProjectIndexRoute: typeof PProjectIndexRoute
  PProjectReviewTaskIdRoute: typeof PProjectReviewTaskIdRoute
  PProjectRunsRunIdRoute: typeof PProjectRunsRunIdRoute
  PProjectTasksTaskIdRoute: typeof PProjectTasksTaskIdRoute
  PProjectReviewIndexRoute: typeof PProjectReviewIndexRoute
  PProjectRunsIndexRoute: typeof PProjectRunsIndexRoute
}

const PProjectRouteChildren: PProjectRouteChildren = {
  PProjectAdrsRoute: PProjectAdrsRoute,
  PProjectBoardRoute: PProjectBoardRouteWithChildren,
  PProjectFilesRoute: PProjectFilesRoute,
  PProjectInboxRoute: PProjectInboxRoute,
  PProjectSettingsRoute: PProjectSettingsRoute,
  PProjectTriggersRoute: PProjectTriggersRoute,
  PProjectIndexRoute: PProjectIndexRoute,
  PProjectReviewTaskIdRoute: PProjectReviewTaskIdRoute,
  PProjectRunsRunIdRoute: PProjectRunsRunIdRoute,
  PProjectTasksTaskIdRoute: PProjectTasksTaskIdRoute,
  PProjectReviewIndexRoute: PProjectReviewIndexRoute,
  PProjectRunsIndexRoute: PProjectRunsIndexRoute,
}

const PProjectRouteWithChildren = PProjectRoute._addFileChildren(
  PProjectRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  InboxRoute: InboxRoute,
  NowRoute: NowRoute,
  OpenrouterRoute: OpenrouterRoute,
  ResourcesRoute: ResourcesRoute,
  RunpodRoute: RunpodRoute,
  SettingsRoute: SettingsRoute,
  PProjectRoute: PProjectRouteWithChildren,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiAttachmentsProjectTaskIdNameRoute: ApiAttachmentsProjectTaskIdNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
